version: "3.8"
services:
  db:
    container_name: pollsdb
    image: postgres:12.2
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - custom
    environment:
      - POSTGRES_DB=peewee_polls
      - POSTGRES_USER=aj
      - POSTGRES_PASSWORD=ajsecret123
      - PGDATA=/var/lib/postgresql/data
  app:
    container_name: pyapp
    build: ./app
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: ./app
        target: /usr/src/app
    depends_on:
      - db
    networks:
      - custom
    env_file:
      - ./app/env.list

volumes:
  db-data:

networks:
  custom:
    driver: bridge